In [1]:
import pandas as pd
import os

In [2]:
data = []
path = 'output.csv'

In [3]:
df = pd.read_csv(f'{path}')
df

,results/description,results/Name_EN,results/name,results/power,results/address,results/provider,results/latitude,results/longitude,results/evConnectorCount,results/evConnectorAggregation
0,"2x CCS2: 160 kW, Type2: 11 kW",Lotus’s Pinklao,โลตัส ปิ่นเกล้า,160 kW,3 ถนน บรมราชชนนี แขวง อรุณอมรินทร์ เขตบางกอกน้...,Altervim,13.776541,100.478430,NaN,NaN
1,"2x CCS2: 160 kW, Type2: 11 kW",Lotus's Sukhapiban 1,โลตัส สุขาภิบาล 1,160 kW,629 799 ถนน นวมินทร์ แขวง นวลจันทร์ เขต บึงกุ่...,Altervim,13.824856,100.658874,NaN,NaN
2,"4x CCS2: 150 kW, 2x Type2: 11 kW",Lotus's North Ratchapruek,โลตัส นอร์ธ ราชพฤกษ์,150 kW,"ถนนราชพฤกษ์, ตำบลอ้อมเกร็ด อำเภอปากเกร็ด นนทบุ...",Altervim,13.912543,100.451431,NaN,NaN
3,"2x CCS2: 60 kW, Type2: 11 kW",Lotus's Ang Thong,โลตัส อ่างทอง,60 kW,เลขที่ 73 ถ.เลี่ยงเมือง ต.โพสะ อ.เมืองอ่างทอง ...,Altervim,14.580418,100.460229,NaN,NaN
4,"2x CCS2: 150 kW, Type2: 11 kW",Lotus's Rojana,โลตัส โรจนะ,150 kW,เลขที่ 101 ม. 3 ต.สามเรือน อ.บางปะอิน จ.พระนคร...,Altervim,14.311211,100.645342,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2126,2x CCS2: 120 kW,NaN,ปตท บจ.ทองคำทิพย์,120 kW,678 ถ.พระรามที่ 2 แขวงแสมดำ เขตบางขุนเทียน จ.ก...,PTT,13.623612,100.390080,NaN,NaN
2127,"2x CCS2, Type 2: 120 kW",NaN,ปตท บจ. มะขามหย่งขนส่ง,120 kW,222 ตำบล บางพลีน้อย อำเภอบางบ่อ สมุทรปราการ 10560,PTT,13.573034,100.910155,NaN,NaN
2128,"2x CCS2, Type 2: 120 kW",NaN,ปตท บจ.สุภาภรณ์ พลังงาน,120 kW,18/18 หมู่ 9 ถ.พนมสารคราม-สัตหีบ ต.หัวสำโรง อ....,PTT,13.609018,101.306732,NaN,NaN
2129,"2x CCS2, Type 2: 120 kW",NaN,ปตท บจ.ธิติปิโตรเลียม (2014),120 kW,337/4 ม.7 ต.บ่อวิน อ.ศรีราชา จ.ชลบุรี 20230,PTT,13.036532,101.136207,NaN,NaN
2130,2x CCS2: 120 kW,NaN,ปตท บจ.ต้นคิดปิโตรเลียม,120 kW,42 ถ.ราชพฤกษ์ แขวงปากคลองภาษีเจริญ เขตภาษีเจริ...,PTT,13.714972,100.462778,NaN,NaN

In [5]:
df.describe()

,results/latitude,results/longitude,results/evConnectorCount,results/evConnectorAggregation
count,2131.000000,2131.000000,0.0,0.0
mean,14.008564,100.762062,NaN,NaN
std,2.424008,1.216427,NaN,NaN
min,5.770530,97.934235,NaN,NaN
25%,13.590790,100.237308,NaN,NaN
50%,13.808750,100.575281,NaN,NaN
75%,14.886211,101.022219,NaN,NaN
max,20.427330,105.426253,NaN,NaN

In [4]:
print(df["results/description"].unique())
print(len(df["results/description"].unique()))

['2x CCS2: 160 kW, Type2: 11 kW' '4x CCS2: 150 kW, 2x Type2: 11 kW'
 '2x CCS2: 60 kW, Type2: 11 kW' '2x CCS2: 150 kW, Type2: 11 kW'
 'CCS2: 118 kW, Type2: CLOSED' 'CCS2: 35 kW, Type2: 22 kW'
 'Type1: 11 kW, Type2: 7x 11 kW, CCS2: 38 kW, CLOSED  B1'
 'Type2: 22 kW, CCS2: CLOSED' 'Type2: 22 kW, CCS2: 2x 150 kW'
 'Type1: 22 kW, CLOSED, Type2: 2x 22 kW, CCS2: 40 kW'
 'Type1: 22 kW, Type2: 22 kW, CCS2: CLOSED' 'CCS2: 40 kW'
 'CCS2: 2x 118 kW, Type2: CLOSED' 'CCS2: 75 kW, Type2: 22 kW'
 'Type2: 22 kW, CCS2: 2x 110 kW' 'CCS2: 2x 40 kW, Type2: 22 kW'
 'Type2: 22 kW, CCS2: 90 kW' 'CCS2: 75 kW, CLOSED'
 'CCS2: 75 kW, Type2: CLOSED' 'Type2: 5x 11 kW, CCS2: CLOSED'
 'CCS2: 103 kW, Type2: CLOSED' 'CCS2: 6x 150 kW' 'CCS2: 4x 150 kW'
 'CCS2: CLOSED, Type2: 11 kW, CLOSED, Type1: CLOSED, -'
 'CCS2: 2x 110 kW, Type2: CLOSED'
 'Type1: 22 kW, CLOSED, Type2: 5 kW, CLOSED, CCS2: 90 kW, CLOSED'
 'Type2: 5 kW, CLOSED, CCS2: 2x 90 kW' 'CCS2: 2x 117 kW, Type2: CLOSED'
 'CCS2: 2x 150 kW' 'CCS2: 150 kW, CLOSED'
 'Type1: 22 kW, Type2: 5 kW, CCS2: 2x 90 kW'
 'CCS2: 2x 116 kW, Type2: CLOSED' 'CCS2: 2x 152 kW'
 'Type2: 3x 22 kW, CCS2: 4x 38 kW'
 'Type2: 22 kW, CLOSED, CCS2: 110 kW, CLOSED' 'Type2: 22 kW, CCS2: 75 kW'
 'CCS2: 150 kW, CLOSED, -' 'Type2: 22 kW, CLOSED, CCS2: CLOSED, -'
 'Type2: 22 kW, CLOSED, CCS2: 135 kW, CLOSED'
 'CCS2: 110 kW, CLOSED, Type2: CLOSED' 'Type2: 22 kW, CCS2: 2x 90 kW'
 'Type2: 5 kW, CCS2: 2x 110 kW ' 'CCS2: 75 kW, CLOSED, Type2: CLOSED'
 'CCS2: 3x 150 kW' 'CCS2: 6x 300 kW'
 'Type2: 22 kW, CLOSED, CCS2: 90 kW, CLOSED'
 'CCS2: 102 kW, CLOSED, Type2: CLOSED'
 'Type1: 22 kW, Type2: 22 kW, CCS2: 2x 90 kW '
 'CCS2: 110 kW, CLOSED, Type2: 22 kW, CLOSED' 'CCS2: 3x 180 kW'
 'CCS2: 4x 300 kW' 'CCS2: 7x 180 kW' 'CCS2: 180 kW, CLOSED'
 'Type2: 3x 11 kW, CCS2: 2x 90 kW' 'CCS2: 4x 360 kW'
 'Type2: 22 kW, CLOSED, CCS2: CLOSED, Type1: 7 kW, CLOSED'
 'CCS2: 59 kW, Type2: CLOSED' 'CCS2: 135 kW, CLOSED, Type2: 22 kW'
 'Type2: 22 kW, CCS2: 59 kW' 'CCS2: 2x 110 kW, Type2: 22 kW'
 'Type2: 2x 22 kW, CCS2: 2x 90 kW'
 'Type1: CLOSED, Type2: 22 kW, CCS2: 2x 97 kW' 'CCS2: 3x 300 kW'
 'CCS2: 3x 152 kW' 'Type1: 5 kW, CLOSED, Type2: 11 kW, CCS2: 2x 90 kW'
 'Type2: 22 kW, CLOSED, CCS2: CLOSED' 'CCS2: 88 kW, CLOSED, Type2: CLOSED'
 'CCS2: 38 kW' 'Type2: 22 kW, CCS2: 2x 110 kW, -'
 'Type2: 5 kW, CCS2: 2x 110 kW' 'CCS2: 300 kW, CLOSED' 'CCS2: 8x 180 kW'
 'Type2: 5 kW, CLOSED, CCS2: 2x 110 kW'
 'CCS2: 117 kW, CLOSED, Type2: CLOSED' 'CCS2: 110 kW, Type2: CLOSED'
 'CCS2: 135 kW, CLOSED, Type2: CLOSED' 'CCS2: CLOSED, Type2: 2x 22 kW'
 'CCS2: 7x 360 kW' 'CCS2: 6x 360 kW' 'Type2: 22 kW, CCS2: 110 kW '
 'Type2: 22 kW, CLOSED, CCS2: 75 kW, CLOSED' 'CCS2: 2x 360 kW'
 'Type2: 22 kW, CCS2: 2x 110 kW ' 'CCS2: 5x 631 kW'
 'CCS2: 30 kW, Type2: 22 kW' 'Type2: 22 kW, CCS2: 110 kW, CLOSED, -'
 'Type2: 2x 5 kW, CCS2: 2x 90 kW' 'CCS2: 30 kW, CLOSED, Type2: CLOSED'
 'Type1: 22 kW, CLOSED, Type2: 5 kW, CLOSED, CCS2: 90 kW'
 'CCS2: 58 kW, Type2: CLOSED' 'Type2: 22 kW, CCS2: 110 kW'
 'Type2: 22 kW, CCS2: 75 kW, CLOSED' 'CCS2: 118 kW, CLOSED, Type2: CLOSED'
 'Type2: 22 kW, Type1: 22 kW, CCS2: 2x 90 kW' 'CCS2: 7x 150 kW'
 'Type1: 22 kW, CCS2: 110 kW, CLOSED, Type2: CLOSED '
 'CCS2: 135 kW, CLOSED' 'Type1: , Type2: 11 kW, CCS2: 2x 90 kW'
 'Type2: 2x 22 kW, CCS2: 90 kW' 'Type2: 22 kW, CCS2: 2x 118 kW'
 'CCS2: 2x 40 kW' 'CCS2: 51 kW, Type2: CLOSED'
 'CCS2: 90 kW, CLOSED, Type2: CLOSED' 'Type2: 3x 22 kW, CCS2: 2x 75 kW'
 'Type2: 22 kW, CCS2: 58 kW' 'Type2: 22 kW, CCS2: 150 kW, CLOSED'
 'Type2: 22 kW, Type1: 5 kW, CCS2: 90 kW'
 'Type1: 11 kW, Type2: 22 kW, CCS2: 2x 75 kW'
 'Type2: 7 kW, CLOSED, CCS2: 118 kW '
 'Type1: 22 kW, CCS2: 110 kW, CLOSED, Type2: CLOSED' 'CCS2: 5x 150 kW'
 'CCS2: 5x 180 kW' 'Type1: 22 kW, Type2: 22 kW, CLOSED, CCS2: 90 kW'
 'Type2: 22 kW, CCS2: 2x 50 kW' 'Type2: 2x 22 kW, CCS2: 2x 118 kW'
 'CCS2: 20 kW, Type2: 2x 22 kW' 'CCS2: 90 kW, Type2: 2x 22 kW'
 'CCS2: 150 kW' 'Type2: 5 kW, CCS2: 75 kW'
 'CCS2: 110 kW, CLOSED, Type2: 5 kW, CLOSED'
 'CCS2: 135 kW, CLOSED, Type2: 5 kW, CLOSED'
 'Type2: 5 kW, CCS2: 2x 118 kW' 'Type2: 2x 22 kW, CCS2: CLOSED'
 'CCS2: 2x 115 kW, Type2: CLOSED' 'CCS2: 110 kW, CLOSED, Type2: 22 kW'
 'CCS2: 115 kW, CLOSED' 'CCS2: 9x 150 kW'
 'CCS2: 2x 90 kW, Type2: 2x 22 kW' 'CCS2: 115 kW, CLOSED, Type2: CLOSED'
 'CCS2: 117 kW, Type2: CLOSED' 'Type2: 22 kW, CCS2: 110 kW, CLOSED'
 'CCS2: 7x 152 kW' 'CCS2: 2x 75 kW, Type2: CLOSED'
 'Type2: 22 kW, CLOSED, CCS2: 150 kW, CLOSED'
 'Type1: 22 kW, CLOSED, Type2: 22 kW, CLOSED, CCS2: 90 kW, CLOSED'
 'Type1: 11 kW, Type2: 2x 22 kW, CCS2: 2x 50 kW'
 'CCS2: 2x 55 kW, Type2: CLOSED'
 'Type1: 22 kW, Type2: 22 kW, CCS2: 90 kW, CLOSED' 'CCS2: 300 kW'
 'CCS2: 2x 300 kW' 'CCS2: 2x 58 kW, Type2: 22 kW'
 'Type2: 11 kW, CCS2: 30 kW' 'CCS2: 38 kW, Type2: 2x 22 kW'
 'Type2: 22 kW, CCS2: 50 kW' 'CCS2: 2x 75 kW, Type2: 2x 22 kW'
 'CCS2: 2x 38 kW, Type2: 2x 22 kW'
 'Type2: 22 kW, CCS2: 2x 75 kW, FN Factory Outlet ' 'CCS2: 2x 100 kW'
 'CCS2: 50 kW, Type2: CLOSED' 'CCS2: 3x 100 kW'
 'CCS2: 2x 50 kW, Type2: CLOSED' 'CCS2: 2x 50 kW, Type2: 22 kW'
 'Type2: CLOSED, Type1: CLOSED, CCS2: 2x 40 kW'
 'CCS2: 2x 35 kW, Type2: CLOSED' 'CCS2: 12x 75 kW, Type2: CLOSED'
 'Type2: 22 kW, Type1: 22 kW, CCS2: 50 kW'
 'CCS2: 40 kW, CLOSED, Type2: CLOSED' 'CCS2: 20 kW, Type2: CLOSED'
 'Type1: 22 kW, Type2: 22 kW, CCS2: 2x 50 kW'
 'CCS2: CLOSED, Type2: 22 kW, CLOSED'
 'Type2: 22 kW, Type1: 22 kW, CCS2: 2x 75 kW'
 'CCS2: 50 kW, CLOSED, Type2: 22 kW, CLOSED'
 'Type1: 22 kW, Type2: 22 kW, CLOSED, CCS2: 2x 50 kW'
 'CCS2: 2x 35 kW, Type2: 2x 22 kW'
 'Type2: 22 kW, CCS2: 2x 75 kW, Type1: CLOSED'
 'Type1: 11 kW, Type2: 22 kW, CLOSED, CCS2: 2x 50 kW'
 'Type2: 2x 22 kW, CCS2: 2x 50 kW' 'Type2: 22 kW, CCS2: 2x 65 kW'
 'Type2: 22 kW, CCS2: 2x 58 kW' 'CCS2: 2x 40 kW, Type2: CLOSED'
 'Type2: 22 kW, CCS2: 2x 75 kW'
 'Type2: 22 kW, Type1: 22 kW, CCS2: 2x 50 kW'
 'Type2: CLOSED, Type1: CLOSED, CCS2: 50 kW'
 'CCS2: 2x 100 kW, Type2: CLOSED' 'Type2: 22 kW, CLOSED, CCS2: 2x 50 kW'
 'CCS2: 50 kW, CLOSED, Type2: CLOSED' 'Type2: 3x 22 kW, CCS2: 2x 40 kW'
 'CCS2: 100 kW, Type2: CLOSED' 'CCS2: 75 kW, CLOSED, Type2: 22 kW'
 'CCS2: 2x 135 kW, Type2: CLOSED'
 'Type2: 22 kW, CLOSED, CCS2: 50 kW, CLOSED'
 'Type2: 22 kW, CCS2: 2x 40 kW' 'CCS2: 50 kW, CLOSED, Type1: CLOSED'
 'Type2: 4x 11 kW, CCS2: 75 kW, CLOSED' '2x CCS2 60 kW'
 'CCS2 50 kW, CHAdeMO 50 kW, Type2 22 kW'
 'CCS2 50 kW, CHAdeMO 50 kW, Type2 22 kW, CCS2 90 kW' 'CCS2 90 kW'
 'CCS2 90 kW, 2x CCS2 120 kW' 'CCS2 90 kW, CCS2 90 kW'
 'CCS2 100 kW, CHAdeMO 100 kW, Type2 22 kW, Type2 22 kW'
 '2x CCS2 125 kW, Type2 22 kW' '2x CCS2 125 kW'
 '2x CCS2 125 kW, 2x CCS2 60 kW'
 'CCS2 100 kW, CHAdeMO 100 kW, Type2 22 kW'
 'CCS2 50 kW, CHAdeMO 50 kW, Type2 22 kW, Type2 7 kW'
 'CCS2 40 kW, CHAdeMO 40 kW' 'CCS2 100 kW, CHAdeMO 100 kW'
 'CCS2 50 kW, CHAdeMO 50 kW, Type2 43 kW'
 'Type2 22 kW, Type2 22 kW, CCS2 60 kW, CHAdeMO 60 kW'
 'CCS2 60 kW, CHAdeMO 60 kW, 2x CCS2 125 kW' '2x CCS2 200 kW'
 '2x CCS2 100 kW, 2x CCS2 100 kW' '2x CCS2 100 kW'
 'CCS2 30 kW, Type2 22 kW' 'Type2 22 kW, Type2 22 kW, 2x CCS2 30 kW'
 '2x CCS2 120 kW' '2x CCS2 100 kW, CCS2 100 kW, CHAdeMO 100 kW'
 '2x CCS2 50 kW' '2x CCS2 150 kW'
 'CCS2 30 kW, CCS2 30 kW, CCS2 30 kW, CCS2 30 kW' nan '6x CCS2' '1x CCS2'
 '2x CCS2' 'ชั้น 2'
 '11 Superchargers, 10:00am - 10:00pm, 3rd floor parking lot'
 '8 Superchargers, available 24/7, B1 floor parking lot A15-A16'
 '10 Superchargers, 10:00am - 10:00pm, 2nd floor parking lot D6-E6'
 '8 Superchargers, available 24/7, Outdoor parking'
 '9 Superchargers, available 24/7, B1 floor parking lot G36-G37 & F36-F38'
 '4 Superchargers, 10:00am - 10:00pm, 1st floor parking lot F09'
 '6 Superchargers, available 24/7, B1 (LG) floor parking lot'
 '8 Superchargers, 10:00am - 10:00pm, G floor parking lot (Star Zone) 47b-47e'
 '12 Superchargers, available 24/7, 6th floor parking lot C05-C07'
 '8 Superchargers, 10:00am - 9:00pm, Parking B building, 3rd floor'
 'CCS2, CHAdeMO, Type 2' '4x CCS2, 2x Type 2' 'CCS2, Type 2'
 '3x CCS2, CHAdeMO, 5x Type 2' 'CCS2, 3x Type 2'
 'CCS2: 50 kW, CHAdeMO: 50 kW, Type2: 22 kW, Type2: 50 kW'
 '2x CCS2: 60 kW, Type2: 22 kW' '2x CCS2: 60 kW'
 '2x CCS2: 60 kW, 2x Type2: 22 kW'
 'CCS2: 90 kW, CHAdeMO: 90 kW, Type2: 90 kW' 'CCS2: 50 kW, Type2: 22 kW'
 '2x CCS2: 180 kW' '2x CCS2: 90 kW' '2x CCS2: 90 kW, 2x Type2: 22 kW'
 '12 Superchargers, available 24/7'
 '6 Superchargers, available 24/7, Parking Zone B near Cafe Amazon'
 '6 Superchargers' '2x CCS2: 47 kW' '2x CCS2: 120 kW' '6x CCS2: 120 kW'
 'CCS2: 15 kW, Type2: 7 kW' 'CCS2: 30 kW'
 '2x CCS2: 40 kW, 4x CCS2: 60 kW, 4x Type2: 22 kW, Type2: 7 kW'
 'CCS2: 60 kW, Type2: 22 kW' 'CCS2: 50 kW, CHAdeMO: 50 kW, Type2: 22 kW'
 '2x CCS2: 47 kW, 2x Type2: 22 kW' 'Non-dealership' 'Dealership'
 '2x CCS2, Type 2: 120 kW' '2x CCS2: 120 kW, 2x CCS2: 120 kW'
 '2x CCS2: 120 kW,  7kW: Type 2' ' 22kW: 2x Type 2, 2x CCS2: 120 kW'
 'Delta AC Mini Plus: Type 2, 2x CCS2: 120 kW'
 ' 22kW: 2x Type 2, 2x CCS2: 120 kW, 2x CCS2: 120 kW'
 'Delta AC Mini Plus: Type 2, 2x CCS2, Type 2: 120 kW'
 ' 7kW: Type 2, 2x CCS2: 120 kW'
 ' 7kW: Type 2,  22kW: 2x Type 2, 2x CCS2, Type 2: 120 kW'
 ' 7kW: Type 2, 2x CCS2, Type 2: 120 kW'
 'StarCharge Nova V2: 2x CCS2: 120 kW, StarCharge Nova V2: 2x CCS2: 120 kW, StarCharge Nova V2: 2x CCS2: 120 kW'
 '2x CCS2, Type 2: 120 kW,  7kW: Type 2'
 '2x CCS2, Type 2: 120 kW, 2x CCS2, Type 2: 120 kW'
 'Teison TS-EDW40-001: 2x CCS2' 'CCS2, CHAdeMO, Type 2: 120 kW']
269